// <auto-generated />
namespace SCRP.DataAccessLayer.Concrete.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mg2110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg2110));
        
        string IMigrationMetadata.Id
        {
            get { return "202005141810347_mg2110"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
